@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitdownload('maven')
                }
            }
        }
        stage('Build')
        {
            steps
            {
                script
                {
                    cicd.buildartifact()
                }
            }
        }
        stage('Deployment')
        {
            steps
            {
                script
                {
                    cicd.deploytomcat("Declarativepipelinewithsharedlibraries","172.31.19.199","testapp")
                }
            }
        }
        stage('Testing')
        {
            steps
            {
                script
                {
                    cicd.gitdownload("FunctionalTesting")
                    cicd.runselenium("Declarativepipelinewithsharedlibraries")
                }
            }
        }
        stage('Delivery')
        {
            steps
            {
                script
                {
                    cicd.deliverytomcat("Declarativepipelinewithsharedlibraries","172.31.36.233","prodapp")
                }
            }
        }
    }
}
