@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitdownload('maven')
                }
            }
        }
        stage('Build')
        {
            steps
            {
                script
                {
                    cicd.buildartifact()
                }
            }
        }
    }
}

